<?php

namespace ricco\ticket\models;

use Yii;

/**
 * This is the model class for table "ticket_body".
 *
 * @property integer $id
 * @property integer $id_head
 * @property integer $client
 * @property string $name_user
 * @property string $text
 * @property string $date
 *
 * @property TicketHead[] $ticketHeads
 */
class TicketBody extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ticket_body';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['text'], 'required'],
            [['text'], 'string'],
            [['date', 'name_user', 'id_head'], 'safe'],
            [['name_user'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name_user' => 'Name User',
            'text' => 'Text',
            'date' => 'Date',
        ];
    }

    /**
     * Перед сохранением указываем имя пользователя который делает ответ
     * Если ответ пишет администратор, делаем соответствующий статус
     * 
     * @param bool $insert
     * @return bool
     */
    public function beforeSave($insert)
    {
        $this->name_user = Yii::$app->user->identity['username'];
        if (Yii::$app->user->identity->isAdmin) {
            $this->client = 1;
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
